from game.game import *

# Testeo diagonales
t = Connect4(7,6,4)
t.move(3)
t.move(4)
t.move(4)
t.move(5)
t.move(6)
t.move(5)
t.move(5)
t.move(6)
t.move(6)
t.move(0)
t.move(6)
t.show()
print(t.check_diag_2(2,6),t.check_diag_2(3,5),t.check_diag_2(4,4),t.check_diag_2(5,3))

# Testeo diagonales
t = Connect4(7,6,4)
t.move(3)
t.move(2)
t.move(2)
t.move(1)
t.move(0)
t.move(1)
t.move(1)
t.move(0)
t.move(0)
t.move(6)
t.move(0)
print(t.current_player)
t.show()
print(t.check_diag_1(2,0),t.check_diag_1(3,1),t.check_diag_1(4,2),t.check_diag_1(5,3))